language: java
script: "mvn verify"
jdk:
  - oraclejdk7
  - openjdk6
before_install:
  - "wget -O- http://chromedriver.googlecode.com/files/chromedriver_linux32_26.0.1383.0.zip | funzip > /usr/bin/chromedriver"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
